### ISSUE TITLE
Always top 15players 

### ISSUE THREAD

**Issue by krustymk** [DevelopGravity/Fluid-MC-Stats#23]
I presume it the following entry in the config.php?

```php
$player_on_top = "3";
```

If it is it doesnt seem to be working

**Comment by ZacharyDuBois** [comment]
Yes, that would be the value to change. I am not sure we ever implemented it. It should be fairly simple. I am having @Lolmewn send me a copy of a DB that has more than 3 users in it. Mine only has 3 :(. Due to the timezone difference, he will probably get back to me tomorrow with it. Thanks for the report :)

**Comment by ZacharyDuBois** [comment]
@Lolmewn provided me with a database. Fixed in the referenced commit :) Thanks for the report!

**Comment by ZacharyDuBois** [comment]
Also, you can download the master repo right now if you want. It currently works on the test site.

**Comment by krustymk** [comment]
Working a treat!! Top man

**Comment by ZacharyDuBois** [comment]
Great :)
